shared:
  title: タイトル
  tag: カテゴリー
  edit_size: 30x35
  public_status: 1
  private_status: 2
  draft_status: 3
post:
  show:
    # ---- ユーザーホームにて,一ページに表示する量 ---- #
    user_posts_index: 3
  index:
    # ---- 記事一覧の一ページ分のインデックス数 ---- #
    one_page_posts_index: 5
comment:
  show:
    # ---- ユーザーホームにて,一ページに表示する量 ---- #
    user_comments_index: 3

